#!/bin/bash

# Running this will display a filterable list of modules
# Once you select one, you will navigate to it
# You can call it with an argument to be used as a pre-filter on the module list

# Requires 'fzf', I highly recommend it.
# https://github.com/junegunn/fzf
# In this case, 'fzf' is reading from stdin

# USAGE EXAMPLES
# gm              (will present the full list of modules)
# gm segments     (will present a list of modules pre-filtered by "segments")

function gm() {
	# The optional filter pattern. If none is given, all modules will be shown
	local PATTERN
	PATTERN="$*"

	# Get the module path
	local MODULE_PATH
	MODULE_PATH="$(
		list_modules |

			# Pass the results to 'fzf' so the user can choose. Also passes the pattern as a default query.
			fzf \
				--exit-0 \
				--no-multi \
				--query "${PATTERN}" \
				--select-1 \
				--height "50%" \
				--reverse \
			;
	)"

	# If you actually chose a module path, navigate to it. Otherwise do nothing.
	if [ -n "${MODULE_PATH}" ]; then
		cd "$(git rev-parse --show-toplevel)/${MODULE_PATH}" || return 1
	fi
}
