#!/bin/bash

function gw() {
	local dir="."

	while [[ -d "${dir}" ]]; do
		if [[ -x "${dir}/gradlew" ]]; then
			echo "Using Gradle wrapper at $(realpath ${dir})"

			"${dir}/gradlew" "$@"

			return
		fi

		dir="${dir}/.."
	done

	echo "Using global Gradle executable"
	gradle "$@"
}
