#!/bin/bash

# uses fd for file searching (https://github.com/sharkdp/fd)

REPO_NAME="$(git config remote.origin.url)"

HEADER_STRING="<C-o> Open result on Github
<C-y> Copy result Github link
<Enter> Open result in primary editor
<A-Enter> Open result in secondary editor
"

if [ -z "${FDF_MAIN_EDITOR_COMMAND}" ]
then
	FDF_MAIN_EDITOR_COMMAND="execute-silent(subl {})"
fi
if [ -z "${FDF_SECONDARY_EDITOR_COMMAND}" ]
then
	FDF_SECONDARY_EDITOR_COMMAND="execute-silent(idea {})"

	# FDF_SECONDARY_EDITOR_COMMAND="become(nvim +{2} {})"
fi

BASE_DIR="$(git rev-parse --show-prefix)"

FZF_ARGS=(
	--bind="ctrl-o:execute-silent(gh browse -R '${REPO_NAME}' ${BASE_DIR}{})"
	--bind="ctrl-y:execute(echo 'Copying link to {}...' && gh browse -R '${REPO_NAME}' --no-browser ${BASE_DIR}{} | tr -d '\n' | pbcopy)"
	--bind="enter:${FDF_MAIN_EDITOR_COMMAND}"
	--bind="alt-enter:${FDF_SECONDARY_EDITOR_COMMAND}"
	--bind="ctrl-space:accept"

	--exit-0
	--header-first
	--header="$HEADER_STRING"
	--info="inline"
	--layout=reverse
	--no-mouse
	--preview="bat --color=always {} 2>/dev/null || eza --all --long --header --icons --sort=type '{}'"
	--preview-window="down:70%"
	--tiebreak=index
)

# Fields are: 1: path

fd "$@" | fzf "${FZF_ARGS[@]}"
