#!/bin/bash

filters=(
	# Exclude any files that are inside a 'src' folder since we only want module roots
	':!:**/src/**'
	# Exclude any files that are inside a 'samples' folder since those are probably not true sources
	':!:**/samples/**'
	# Exclude any files inside of portal-web/test since they are not true sources either
	':!:portal-web/test/**'

	'*.bnd'
	'*build.gradle'
	'*build.xml'
	'*client-extension.yaml'
	'*package.json'
	'*pom.xml'
	'*settings.gradle'
)
git -C "$(git rev-parse --show-toplevel)" ls-files -- "${filters[@]}" |

	# Strip the filename, leaving just the directory name
	# 	This is WAY faster than using "dirname"
	#
	# Strip the trailing forward-slash
	# Delete any empty lines
	sed -E \
		-e 's,[^/]*$,,g' \
		-e 's,/$,,g' \
		-e '/^$/d' |

	# Gets rid of any duplicates in case a module has more than one *.bnd file
	sort -u
