#!/bin/bash

STARTUP_COMMANDS=(
	open
	sync
	# sync-ee
	# connect-to-vpn
)

function run_command() {
	command="${1}"

	echo ""
	echo "Running command: ${command}"
	"cmd_${command}"
}

STARTUP_APPS=(
	Obsidian
	"Brave Browser"
	"Sublime Merge"
	# TaskPaper
	Things3
	# SelfControl
)
function cmd_open() {
	for app in "${STARTUP_APPS[@]}"; do
		echo "Hello $app"
		open --background -a "$app" &
	done
}

function cmd_sync() {
	gh repo sync drewbrokke/liferay-portal --source liferay/liferay-portal
	gh repo sync liferay-devtools/liferay-portal --source liferay/liferay-portal

	(
		cd "$LIFERAY/liferay-portal" || exit 1
		git fetch origin master --no-tags
		git fetch devtools master --no-tags
		git fetch upstream master --no-tags
		git fetch brian master --no-tags
	)
}

EE_BRANCHES=(
	# master
	# release-2025.q1
	# release-2024.q4
	# release-2024.q3
	# release-2024.q2
	# release-2024.q1
	# release-2023.q4
	# release-2023.q3
	7.3.x
	7.2.x
	7.1.x
	7.0.x
)
function cmd_sync-ee() {
	for branch in "${EE_BRANCHES[@]}"; do
		gh repo sync drewbrokke/liferay-portal-ee \
			--force \
			--branch ${branch} \
			--source liferay/liferay-portal-ee ||
		echo "Could not sync branch ${branch}"

		(
			cd "$LIFERAY/liferay-portal-ee" || exit 1
			git fetch upstream "${branch}" --no-tags
		)
	done

}

function cmd_connect-to-vpn() {
	# shellcheck disable=SC2317
	m vpn start 9F145C81-E15C-4E0F-AB4B-DF9DB33FBFE4
}

if [ $# -gt 0 ]; then
	command="${1}"

	run_command "${command}"
else
	for command in "${STARTUP_COMMANDS[@]}"; do
		run_command "${command}"
	done
fi
